-- =============================================================
-- Bifrost Remediation Patch
-- Generated by : bifrost v1.0.0
-- Timestamp    : 2026-09-27T13:12:01Z
-- =============================================================
--
-- EXPAND-CONTRACT COMPATIBILITY SHIM
-- ─────────────────────────────────────────────────────────────
-- This patch implements the expand-contract pattern for a
-- zero-downtime schema migration.
--
-- HOW IT WORKS:
-- 1. The physical v2 table (e.g. users_v2) holds the new schema.
-- 2. A VIEW with the original table name (e.g. users) is created
--    on top, synthesizing legacy columns (e.g. 'name') from the
--    new split columns (e.g. first_name || ' ' || last_name).
-- 3. Legacy application code that queries the original table name
--    continues to work without modification.
-- 4. Once all application instances are updated to use the new
--    schema directly, this VIEW can be dropped safely.
--
-- APPLY INSTRUCTIONS:
-- 1. Review this script thoroughly before running in production.
-- 2. Test in a staging environment first.
-- 3. Apply during a low-traffic window.
-- 4. Monitor application error rates for ≥ 10 minutes after apply.
-- =============================================================

BEGIN;

-- Step 1: Create the backward-compatible VIEW.
-- This view exposes the legacy column names so old queries still work.
CREATE VIEW IF NOT EXISTS users AS
SELECT
    id,
    (first_name || ' ' || last_name) AS name,
    email,
    first_name,
    last_name
FROM users_v2;

-- Step 2: Verify the view is queryable.
-- This SELECT must return rows if seed data exists.
SELECT * FROM users LIMIT 1;

COMMIT;

-- =============================================================
-- Patch applied successfully.
-- Legacy queries are now compatible with the new schema.
-- To remove the shim once all clients are migrated:
--   DROP VIEW IF EXISTS users;
-- =============================================================
